server:
  port: 7001

eureka:
  instance:
    #eureka服务端的实例名称
    hostname: eureka7001.com
    #Eureka客户端向服务端发送心跳的时间间隔，默认为30秒
    lease-renewal-interval-in-seconds: 1
    #Eureka服务端在最后一次收到心跳后等待时间上限，默认为90秒，超时将剔除服务
    lease-expiration-duration-in-seconds: 2
  client:
    #false表示不向注册中心注册自己（注册中心）
    register-with-eureka: false
    #false表示自己就是注册中心，我的职责就是维护服务实例，并不需要检索服务
    fetch-registry: false
    service-url:
      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://eureka7002.com:7002/eureka
  server:
    #关闭eureka自我保护机制
    enable-self-preservation: false
    #剔除服务时间间隔
    eviction-interval-timer-in-ms: 2000
